# Generated by Django 3.1.2 on 2020-11-25 23:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('peso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Peso')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('stock', models.BigIntegerField(verbose_name='Stock')),
                ('animal_id', models.ManyToManyField(to='producto.Animal')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
